"""
Multi-lingual clinical rules and patterns for 12 Knee MRI diagnostic targets.
"""

RULES = {
    'ACL': [
        r'acl\s*(?:tear|rupture|sprain|injury|disruption|avulsion|laxity)',
        r'anterior\s+cruciate\s+ligament.*?(?:tear|ruptur|sprain|injur|disrupt|avuls|laxity|gap|defect)',
        r'rotura\s+(?:completa|parcial|de\s+fibras)?\s*(?:del\s+)?(?:lca|ligamento\s+cruzado\s+anterior)',
        r'(?:lca|ligamento\s+cruzado\s+anterior).*?(?:rotura|desgarro|lesi[oó]n|esguince|avulsi[oó]n)',
        r'(?:déchirure|rupture|lésion).*?(?:lca|ligament\s+croisé\s+antérieur)',
        r'(?:vorderes\s+kreuzband|vkb).*?(?:ruptur|riss|teilruptur|laesie|läsion|insuffizienz|ausriss)',
        r'(?:voorste\s+kruisband|vkb).*?(?:scheur|ruptuur|laesie)',
        r'ön\s+çapraz\s+bağ.*?(?:yırtık|rüptür|kopma|devamsız)',
        r'(?:руптура|увреда).*?предната\s+кръстна\s+връзка',
        r'πρόσθι(?:ος|ου)\s+χιαστ(?:ός|ού).*?(?:ρήξη|κάκωση)',
    ],
    'MCL': [
        r'mcl\s*(?:tear|sprain|injury|rupture|thickening|edema|strain|disruption)',
        r'medial\s+collateral\s+ligament.*?(?:tear|sprain|injur|ruptur|thickening|edema|strain|disrupt|laxity)',
        r'(?:esguince|rotura|lesi[oó]n).*?(?:del\s+)?(?:lcm|ligamento\s+colateral\s+medial|ligamento\s+colateral\s+interno)',
        r'(?:lcm|ligamento\s+colateral\s+medial).*?(?:esguince|rotura|lesi[oó]n|engrosamiento|edema)',
        r'(?:entorse|déchirure|rupture|lésion).*?(?:du\s+)?(?:lcm|ligament\s+collatéral\s+médial|ligament\s+collatéral\s+interne)',
        r'(?:mediales\s+kollateralband|mcl|innenband).*?(?:läsion|laesie|ruptur|riss|zerrung|teilruptur|sprain)',
        r'(?:mediale\s+band|mcl).*?(?:scheur|sprain|ruptuur|letsel)',
        r'medial\s+kollateral\s+ligaman.*?(?:yırtık|sprain|ödem|rüptür)',
        r'έσω\s+πλάγι(?:ος|ου).*?(?:ρήξη|κάκωση|διάταση)',
    ],
    'Medial Meniscus': [
        r'medial\s+menisc(?:us|al).*?(?:tear|rupture|bucket[\s-]handle|flap|root\s+tear|macerat|amputat|resect)',
        r'(?:tear|rupture|bucket[\s-]handle|root\s+tear).*?medial\s+menisc(?:us|al)',
        r'(?:rotura|desgarro|lesi[oó]n|amputaci[oó]n).*?(?:del\s+)?menisco\s+(?:medial|interno)',
        r'menisco\s+(?:medial|interno).*?(?:rotura|desgarro|lesi[oó]n|amputaci[oó]n|en\s+asa\s+de\s+cubo)',
        r'(?:déchirure|rupture|lésion|anse\s+de\s+seau).*?m[ée]nisque\s+(?:m[ée]dial|interne)',
        r'(?:innenmeniskus|medialer\s+meniskus).*?(?:riss|ruptur|korbhenkel|läsion|ausriss|substanzdefekt)',
        r'(?:mediale\s+meniscus|binnenmeniscus).*?(?:scheur|ruptuur|letsel|bucket\s+handle)',
        r'medial\s+menisküs.*?(?:yırtık|rüptür|kova\s+sapı|grade\s+3|grade\s+iii)',
        r'(?:руптура|увреда).*?медиалния\s+менискус',
        r'έσω\s+µηνίσκ(?:ος|ου).*?(?:ρήξη|κάκωση|βλάβη)',
    ],
    'Lateral Meniscus': [
        r'lateral\s+menisc(?:us|al).*?(?:tear|rupture|bucket[\s-]handle|flap|root\s+tear|macerat|amputat)',
        r'(?:tear|rupture|bucket[\s-]handle|root\s+tear).*?lateral\s+menisc(?:us|al)',
        r'(?:rotura|desgarro|lesi[oó]n|amputaci[oó]n).*?(?:del\s+)?menisco\s+(?:lateral|externo)',
        r'menisco\s+(?:lateral|externo).*?(?:rotura|desgarro|lesi[oó]n|amputaci[oó]n|en\s+asa\s+de\s+cubo)',
        r'(?:déchirure|rupture|lésion|anse\s+de\s+seau).*?m[ée]nisque\s+(?:lat[ée]ral|externe)',
        r'(?:au[ßs]enmeniskus|lateraler\s+meniskus).*?(?:riss|ruptur|korbhenkel|läsion|ausriss|substanzdefekt)',
        r'(?:laterale\s+meniscus|buitenmeniscus).*?(?:scheur|ruptuur|letsel)',
        r'lateral\s+menisküs.*?(?:yırtık|rüptür|kova\s+sapı|grade\s+3|grade\s+iii)',
        r'(?:руптура|увреда).*?латералния\s+менискус',
        r'έξω\s+µηνίσκ(?:ος|ου).*?(?:ρήξη|κάκωση|βλάβη)',
    ],
    'Medial OA': [
        r'medial\s*(?:compartment|tibiofemoral)?\s*(?:osteoarthritis|oa|arthrosis|gonarthrosis|degeneration)',
        r'tricompartmental\s*(?:osteoarthritis|oa|arthrosis|chondropathy|chondrosis|gonarthrosis)',
        r'medial\s*(?:femoral\s*condyle|tibial\s*plateau|compartment).*?(?:full[\s-]thickness|grade\s*[34]|grade\s*(?:iii|iv)|severe\s*thinning|loss\s*of\s*cartilage|bone[\s-]on[\s-]bone)',
        r'(?:artrosis|osteoartritis|gonartrosis).*?(?:femorotibial\s*)?medial',
        r'artrosis\s*(?:femorotibial\s*)?(?:interna|medial|tricompartimental|severa)',
        r'(?:arthrose|gonarthrose).*?(?:f[ée]moro[\s-]tibiale\s*)?(?:m[ée]diale|interne|tricompartimentale)',
        r'(?:gonarthrose|arthrose|chondropathie).*?(?:medial|innen|pangonarthrose)',
        r'mediale\s*gonartroz|medial\s*eklem\s*aralığı\s*daral',
        r'остеоартрит.*?медиалн',
    ],
    'PF OA': [
        r'patellofemoral\s*(?:osteoarthritis|oa|arthrosis|chondrosis|chondromalacia|degeneration)',
        r'pf\s*oa',
        r'tricompartmental\s*(?:osteoarthritis|oa|arthrosis|chondropathy|chondrosis|gonarthrosis)',
        r'(?:patella|trochlea|patellar|trochlear).*?(?:full[\s-]thickness|grade\s*[234]|grade\s*(?:ii|iii|iv)|severe\s*thinning|high[\s-]grade|loss\s*of\s*cartilage)',
        r'(?:chondromalacia\s*patella|patellar\s*chondromalacia)',
        r'(?:condromalacia\s*rotuliana|condropat[ií]a\s*(?:rotuliana|patelar|patelofemoral))',
        r'artrosis\s*patelofemoral',
        r'(?:chondropathie|arthrose)\s*(?:r[ée]tropatellaire|patello[\s-]f[ée]morale|patellaire)',
        r'(?:retropatellare\s*chondropathie|femoropatellare\s*arthrose)',
        r'patellar\s*kondromalazi',
        r'χονδροµαλάκυνση\s*επιγονατίδας',
    ],
    'Effusion': [
        r'(?:small|mild|moderate|large|marked|significant|extensive|trace|minimal|some)\s*(?:knee\s+|joint\s+|intra[\s-]articular\s+)?(?:effusion|fluid)',
        r'\b(?:joint\s+effusion|knee\s+effusion|hemarthrosis|lipohemarthrosis)\b',
        r'(?:derrame\s*articular|derrame|lipohemartrosis|hemartrosis)',
        r'(?:épanchement\s*intra[\s-]articulaire|épanchement\s*articulaire|épanchement)',
        r'(?:gelenkerguss|kniegelenkserguss|erguss)',
        r'(?:gewrichtsvocht|vochtuitstorting)',
        r'(?:eklem\s*içi\s*sıvı|mayii\s*artışı|sıvı\s*artışı)',
        r'(?:ставен\s*излив|излив)',
        r'(?:ενδαρθρική\s*συλλογή|ύδραρθρο)',
        r'\bizljev\b',
    ],
    'Synovitis': [
        r'\bsynovitis\b',
        r'synovial\s*(?:thickening|proliferation|hypertrophy|pannus|tissue|inflammation)',
        r'\bsinovitis\b',
        r'proliferaci[oó]n\s*sinovial',
        r'engrosamiento\s*sinovial',
        r'\bsynovite\b',
        r'[ée]paississement\s*synovial',
        r'\bsynovialitis\b',
        r'synoviale\s*proliferation',
        r'sinovit',
        r'sinovyal\s*kalınlaşma',
        r'синовит',
        r'synovial\s*lipoma|lipoma\s*arborescens',
        r'pvns|pigmented\s*villonodular\s*synovitis',
    ],
    "Baker's": [
        r'baker[\'’]?s?\s*cyst',
        r'popliteal\s*cyst',
        r'quiste\s*de\s*baker',
        r'quiste\s*popl[ií]teo',
        r'kyste\s*de\s*baker',
        r'kyste\s*poplit[ée]',
        r'baker[\s-]zyste',
        r'poplitealzyste',
        r'baker[\s-]cyste',
        r'baker\s*kisti',
        r'бекерова\s*киста',
        r'κύστη\s*baker',
    ],
    'Contusion': [
        r'bone\s*(?:contusion|bruise)',
        r'osseous\s*contusion',
        r'trabecular\s*microfracture',
        r'contusi[oó]n\s*[oó]sea',
        r'edema\s*[oó]seo\s*(?:post[\s-]traum[aá]tico|contusional)',
        r'contusion\s*osseuse',
        r'[oe]d[èe]me\s*osseux\s*post[\s-]traumatique',
        r'bone[\s-]bruise',
        r'knochenkontusion',
        r'kontusions[\s-]?[oö]dem',
        r'botcontusie',
        r'kemik\s*kontüzyon',
        r'kontüzyonel\s*kemik\s*iliği\s*ödem',
        r'костномозъчен\s*едем\s*(?:посттравматичен|след\s*травма)',
        r'οστικό\s*οίδηµα\s*\(bone\s*bruise\)',
    ],
    'Fracture': [
        r'(?:acute|subacute|avulsion|tibial|femoral|patellar|fibular|osteochondral|stress|insufficiency)\s*fracture',
        r'\bfracture\b',
        r'\bfractura\b',
        r'\bfraktur\b',
        r'\bfractuur\b',
        r'\bfraktür\b',
        r'фрактура',
        r'κάταγµα',
    ],
    'Lateral OA': [
        r'lateral\s*(?:compartment|tibiofemoral)?\s*(?:osteoarthritis|oa|arthrosis|gonarthrosis)',
        r'tricompartmental\s*(?:osteoarthritis|oa|arthrosis|chondropathy|chondrosis|gonarthrosis)',
        r'lateral\s*(?:femoral\s*condyle|tibial\s*plateau|compartment).*?(?:full[\s-]thickness|grade\s*[34]|grade\s*(?:iii|iv)|severe\s*thinning|loss\s*of\s*cartilage|bone[\s-]on[\s-]bone)',
        r'(?:artrosis|osteoartritis|gonartrosis).*?(?:femorotibial\s*)?lateral',
        r'artrosis\s*(?:femorotibial\s*)?(?:externa|lateral|tricompartimental)',
        r'(?:arthrose|gonarthrose).*?(?:f[ée]moro[\s-]tibiale\s*)?(?:lat[ée]rale|externe|tricompartimentale)',
        r'(?:gonarthrose|arthrose).*?(?:lateral|au[ßs]en|pangonarthrose)',
        r'lateral\s*gonartroz',
    ]
}
